### ISSUE TITLE
Problem with Kaggle

### ISSUE THREAD

**Issue by aliaamiri** [MeikeSteinhilber/sprtt#32]
Many thanks for the package.
I cannot use this package inside a Kaggle notebook. I do not know why Kaggle does not load the package.
Is there any solution to this problem?

**Comment by MeikeSteinhilber** [comment]
Can you send me the error message you are getting?
My first idea would be that Kaggle is not using the latest R version.
Other users seem to have the same problem with other packages in the past:
- https://www.kaggle.com/getting-started/151861
- https://www.kaggle.com/product-feedback/218428

**Comment by aliaamiri** [comment]
Yes, it is not the first time that this happens. Even in the [list of packages available](https://github.com/Kaggle/docker-rcran/blob/main/packages_users) in Kaggle, `sprtt` is missing. The error is:

`Error in library(sprtt) : there is no package called 'sprtt'`

Inevetibally, instead of your package, I used the code provided by [Schnuerch & Erdfelder](https://osf.io/wz8da/).
Anyway, I referenced your package in my notebook and made a discussion topic to inform Kaggle staff about this. 

- https://github.com/Kaggle/docker-rcran/issues/58
- https://www.kaggle.com/product-feedback/303934

**Comment by MeikeSteinhilber** [comment]
Thanks a lot! Especially for the reference! 😃
