### ISSUE TITLE
Change licence from GPL to AGPL

### ISSUE THREAD

**Issue by MeikeSteinhilber** [MeikeSteinhilber/sprtt#33]
There is a loophole in the GPL licence - AGPL fixes that but the rest is the same as before.
https://de.wikipedia.org/wiki/GNU_Affero_General_Public_License

I want to change that with the new 0.2.0 version.

Is that ok @mschnuerch?
Is that ok @Anna-LenaSchubert?

**Comment by mschnuerch** [comment]
Apparently, CC does not recommend using their licenses for software (https://creativecommons.org/faq/#can-i-apply-a-creative-commons-license-to-software).

**Comment by MeikeSteinhilber** [comment]
AGPL seems to be the most resticted open-source software licence. here is a nice overwiev of open-source licenses
https://choosealicense.com/licenses/

**Comment by mschnuerch** [comment]
I also agree with the suggested change to AGPL.
